services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/horilla"
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-web.rule=Host(`hr.keeways.com`)
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-web.entrypoints=web
      - traefik.http.services.keeways-internal-horilla-kzjoae-21-web.loadbalancer.server.port=8000
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-web.service=keeways-internal-horilla-kzjoae-21-web
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-web.middlewares=redirect-to-https@file
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-websecure.rule=Host(`hr.keeways.com`)
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-websecure.entrypoints=websecure
      - traefik.http.services.keeways-internal-horilla-kzjoae-21-websecure.loadbalancer.server.port=8000
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-websecure.service=keeways-internal-horilla-kzjoae-21-websecure
      - traefik.http.routers.keeways-internal-horilla-kzjoae-21-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    networks:
      - dokploy-network
  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: horilla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network 
volumes:
  horilla-data:
networks:
  dokploy-network:
    external: true
